CFLAGS = -std=c++11
CC = g++

target:HW2

HW2: SparseVector.cpp SparseMatrix.cpp main.cpp SparseVector.h SparseMatrix.h
	$(CC) $(CFLAGS) SparseVector.cpp SparseMatrix.cpp main.cpp -o HW2 
clean:
	rm *.o
